import React from 'react';
import { ComponentMeta, ComponentStory } from '@storybook/react';
import Icon from '../icon/Icon';

export default {
  title: 'Icon',
  component: Icon,
  argTypes: {
    color: {
      options: ['primary', 'secondary', 'danger', 'black'],
      control: { type: 'radio' },
    },
    icon: {
      options: [
        'account',
        'add',
        'add-outline',
        'arrow-down',
        'arrow-up',
        'arrow-drop-down',
        'arrow-drop-up',
        'arrow-left',
        'arrow-right',
        'basket',
        'bookmark-off',
        'bookmark-on',
        'call',
        'calendar',
        'call',
        'card',
        'cart',
        'chart',
        'close',
        'close-outline',
        'copy',
        'dashboard',
        'delete',
        'description',
        'done',
        'download',
        'drag-handler',
        'edit',
        'error',
        'error-outline',
        'exit',
        'expand-less',
        'expand-more',
        'filter',
        'find',
        'first-page',
        'gift',
        'help',
        'help-outline',
        'hide',
        'home',
        'idea',
        'info',
        'info-outline',
        'label',
        'last-page',
        'like-fill',
        'like-outline',
        'location',
        'mail',
        'mail-outline',
        'menu',
        'money',
        'more-vert',
        'next',
        'notification',
        'person',
        'photo',
        'prev',
        'question-answer',
        'receipt',
        'remove',
        'remove-outline',
        'send',
        'setting',
        'share',
        'shipping',
        'show',
        'star-fill',
        'star-outline',
        'star-half',
        'store',
        'thumb-down-fill',
        'thumb-up-fill',
        'upload',
      ],
      control: { type: 'select' },
    },
    size: {
      control: { type: 'number' },
    },
  },
} as ComponentMeta<typeof Icon>;

export const Icons: ComponentStory<typeof Icon> = (args) => <Icon {...args} />;
Icons.args = { color: 'primary', icon: 'add', size: 24 };
